keen/keen

package-lock.json, packages/ui-core/src/components/card.component.tsx, packages/ui-core/src/components/card.stories.tsx
=> feat: 🎸 border radius for card component

.circleci/config.yml, package.json
=> ci: 🎡 fix for memory

packages/charts/src/components/legend/legend.stories.tsx, packages/charts/src/components/legend/legend.styles.tsx
=> style: 💄 update styles for legend

packages/charts/src/components/chart-tooltip/chart-tooltip.component.tsx, packages/charts/src/components/chart-tooltip/chart-tooltip.utils.test.tsx, packages/charts/src/components/chart-tooltip/chart-tooltip.utils.ts, packages/ui-core/src/components/tooltip/tooltip.component.tsx
=> feat: 🎸 vertical tooltip position

packages/charts/src/components/legend/legend.styles.tsx
=> style: 💄 re-styling legend items alignment

packages/ui-core/src/components/card/card.component.tsx, packages/widgets/src/components/widget-heading.component.tsx, packages/widgets/src/components/widget-heading.styles.ts, packages/widgets/src/widget-settings.ts
added spacing for title and subtittle + card
=> chore: 🤖 ui adjustments

packages/charts/src/charts/index.ts, packages/charts/src/charts/line/index.ts, packages/charts/src/index.ts, packages/widgets/src/components/area/area-chart.widget.tsx
=> fix: 🐛 Fix for area chart legend bug

.gitignore, packages/ui-core/src/components/index.ts, packages/ui-core/src/components/toggle/__snapshots__/toggle.component.test.tsx.snap, packages/ui-core/src/components/toggle/index.ts, packages/ui-core/src/components/toggle/toggle.component.styles.ts, packages/ui-core/src/components/toggle/toggle.component.test.tsx, packages/ui-core/src/components/toggle/toggle.component.tsx, packages/ui-core/src/components/toggle/toggle.stories.tsx, packages/ui-core/src/index.ts
=> feat: 🎸 toggle

packages/charts/src/charts/donut/donut-chart.component.tsx, packages/charts/src/charts/donut/donut-chart.stories.tsx, packages/charts/src/charts/donut/donut-total.component.tsx, packages/charts/src/theme.ts, packages/charts/src/types.ts
=> fix: 🐛 total label alignment and inner radius slider

packages/charts/src/charts/bubble/bubble-chart.component.tsx, packages/charts/src/charts/bubble/correlation.component.tsx, packages/charts/src/charts/bubble/correlation.styles.ts, packages/charts/src/charts/bubble/tooltip-content.component.tsx
=> style: 💄 bubble chart tooltip

README.MD, package.json, packages/embedded-registration/assets/iframe-socket.html, packages/embedded-registration/index.html, packages/embedded-registration/jest.config.js, packages/embedded-registration/jest.setup.ts, packages/embedded-registration/package.json, packages/embedded-registration/src/app.component.tsx, packages/embedded-registration/src/embedded-registration.tsx, packages/embedded-registration/src/index.ts, packages/embedded-registration/src/types.ts, packages/embedded-registration/tsconfig-webpack.json, packages/embedded-registration/tsconfig.json, packages/embedded-registration/tsconfig.umd.json, packages/embedded-registration/webpack.common.ts, packages/embedded-registration/webpack.config.ts, packages/embedded-registration/webpack.prod.config.ts, yarn.lock
=> chore: 🤖 bootstrap registration

packages/charts/src/components/chart-tooltip/chart-tooltip.component.tsx, packages/charts/src/components/chart-tooltip/chart-tooltip.utils.test.tsx, packages/charts/src/components/chart-tooltip/chart-tooltip.utils.ts
https://metakeen.atlassian.net/browse/FRON-10
=> fix: 🐛 tooltip position

docs/theme-intro.mdx, packages/charts/src/charts/area/area-chart.component.tsx, packages/charts/src/charts/bar/bar-chart.component.tsx, packages/charts/src/charts/bubble/bubble-chart.component.tsx, packages/charts/src/charts/heatmap/heatmap-chart.component.tsx, packages/charts/src/charts/line/line-chart.component.tsx
https://metakeen.atlassian.net/browse/FRON-40
=> docs: ✏️ update for axis title

packages/embedded-registration/index.html, packages/embedded-registration/src/app.component.tsx, packages/embedded-registration/src/embedded-registration.tsx, packages/embedded-registration/src/types.ts, packages/ui-core/src/components/button/__snapshots__/button.component.test.tsx.snap, packages/ui-core/src/components/button/button.styles.ts
added callback for success registration event
=> feat: 🎸 success callback

packages/ui-core/src/components/toggle/__snapshots__/toggle.component.test.tsx.snap, packages/ui-core/src/components/toggle/toggle.component.styles.ts, packages/ui-core/src/components/toggle/toggle.component.tsx, packages/ui-core/src/components/toggle/toggle.stories.tsx, packages/ui-core/src/components/toggle/types.ts
https://metakeen.atlassian.net/browse/FRON-58
=> feat: 🎸 add variant for Toggle

packages/dataviz/package.json, packages/dataviz/webpack.config.ts
This PR resolve the possible issues with styled-components namespaces conflicts.
=> feat: 🎸 dataviz css scope

packages/parser/src/utils/time.utils.test.ts, packages/parser/src/utils/time.utils.ts
https://metakeen.atlassian.net/browse/FRON-136
=> feat: 🎸 support for custom interval

packages/charts/src/charts/bar/bar-tooltip-content.component.tsx, packages/charts/src/charts/bubble/bubble-chart.component.tsx, packages/charts/src/charts/bubble/tooltip-content.component.tsx, packages/charts/src/charts/line/tooltip.component.tsx, packages/charts/src/utils/index.ts, packages/charts/src/utils/tooltip.utils.test.ts, packages/charts/src/utils/tooltip.utils.ts, packages/dataviz/src/stories/bubble-chart.stories.tsx
https://metakeen.atlassian.net/browse/FRON-82
=> feat: 🎸 format tooltip value

packages/ui-core/src/components/alert/alert.styles.ts, packages/ui-core/src/components/error/error.component.tsx, packages/ui-core/src/components/index.ts, packages/ui-core/src/components/input/input.styles.ts, packages/ui-core/src/components/label/label.stories.tsx, packages/ui-core/src/components/label/label.styles.ts, packages/ui-core/src/components/modal-footer/index.ts, packages/ui-core/src/components/modal-footer/modal-footer.styles.ts, packages/ui-core/src/components/modal-header/index.ts, packages/ui-core/src/components/modal-header/modal-header.component.tsx, packages/ui-core/src/components/modal-header/modal-header.styles.ts, packages/ui-core/src/components/modal-header/modal-header.test.tsx, packages/ui-core/src/components/modal/modal.component.test.tsx, packages/ui-core/src/components/modal/modal.component.tsx, packages/ui-core/src/components/modal/modal.stories.tsx, packages/ui-core/src/components/modal/modal.styles.ts, packages/ui-core/src/index.ts
BREAKING CHANGE: modal component interface
=> feat: 🎸 adjust components to styleguide

packages/ui-core/src/components/alert/alert.styles.ts, packages/ui-core/src/components/input/input.styles.ts
https://metakeen.atlassian.net/browse/FEE-46
=> chore: 🤖 adjust error colors

packages/ui-core/src/components/checkbox/checkbox.styles.ts
align tick position for checkbox to match designs
=> chore: 🤖 update checkbox tick position

packages/ui-core/src/components/alert/alert.styles.ts
align `<Alert type='info'>` colors with  ![image](https://user-images.githubusercontent.com/23423731/91849614-9e960680-ec5c-11ea-8c87-ac284903b0ab.png)
=> style: 💄 update alert info colors

packages/charts/src/charts/table/table-chart.component.tsx
fixing ![Screenshot 2020-09-01 at 12 44 31](https://user-images.githubusercontent.com/23423731/91842217-f2502200-ec53-11ea-8f07-0217854d493a.png)
=> fix: 🐛 add tbody to table chart

packages/charts/src/charts/metric/metric-chart.component.test.tsx, packages/charts/src/charts/metric/metric-chart.component.tsx, packages/charts/src/charts/metric/metric-chart.stories.tsx, packages/charts/src/charts/metric/utils/index.ts, packages/charts/src/charts/metric/utils/metric.utils.test.ts, packages/charts/src/charts/metric/utils/metric.utils.ts, packages/storybook-utils/src/select.knobs.ts
https://metakeen.atlassian.net/browse/FEE-109
=> refactor: 💡 metric chart interface

packages/charts/src/charts/bar/bar-chart.fixtures.ts, packages/charts/src/charts/bar/utils/__snapshots__/chart.utils.test.ts.snap, packages/charts/src/charts/bar/utils/chart.utils.ts, packages/charts/src/charts/line/line-chart.fixtures.ts, packages/charts/src/charts/line/line-chart.utils.test.ts, packages/charts/src/components/__snapshots__/grid.utils.test.ts.snap, packages/charts/src/components/grid.component.tsx, packages/charts/src/components/grid.utils.ts, packages/charts/src/types.ts, packages/charts/src/utils/data.utils.ts, yarn.lock
* https://metakeen.atlassian.net/browse/FEE-110
* https://metakeen.atlassian.net/browse/FEE-111
=> fix: 🐛 support negative values in charts

packages/ui-core/src/components/password-validator/password-validator.styles.ts
https://metakeen.atlassian.net/browse/FEE-118
=> fix: 🐛 fix icon overflow in IE11

packages/ui-core/src/components/table/table-cell.component.tsx, packages/ui-core/src/components/table/table-cell.styles.ts, yarn.lock
https://metakeen.atlassian.net/browse/FEE-148
=> fix: 🐛 squashed table cells issue

packages/widgets/src/components/table/table-chart.widget.tsx
https://metakeen.atlassian.net/browse/FEE-156
=> fix: 🐛 render [sub]title when content is provided

packages/charts/src/charts/metric/utils/metric.utils.test.ts, packages/charts/src/charts/metric/utils/metric.utils.ts
https://metakeen.atlassian.net/browse/FEE-159
=> fix: 🐛 metric difference

packages/parser/src/__snapshots__/convertToCsv.test.ts.snap, packages/parser/src/convertToCsv.test.ts, packages/parser/src/convertToCsv.ts, packages/parser/src/index.ts
https://metakeen.atlassian.net/browse/FEE-73
=> feat: 🎸 convertToCSV

packages/parser/README.md, packages/ui-core/src/components/modal/modal.styles.ts
* https://metakeen.atlassian.net/browse/FEE-166
* https://metakeen.atlassian.net/browse/FEE-162
=> fix: 🐛 add zIndex for <Modal/>

packages/charts/src/components/legend/slider/slider.styles.tsx
https://metakeen.atlassian.net/browse/FEE-174
=> fix: 🐛 hide scrollbar in FF

packages/charts/src/charts/funnel/funnel-step.styles.ts
https://metakeen.atlassian.net/browse/FEE-176
=> fix: 🐛 equal size of funnel steps

packages/charts/src/charts/funnel/funnel-step.styles.ts
https://metakeen.atlassian.net/browse/FEE-181
=> fix: 🐛 funnel steps overflow in FF

packages/charts/src/charts/table/components/header-row/header-row.styles.ts
https://metakeen.atlassian.net/browse/FEE-182
=> fix: 🐛 z-index for table header added

packages/charts/src/components/ruler.utils.ts
https://metakeen.atlassian.net/browse/FEE-179
=> fix: 🐛 axis label rotation

packages/widget-picker/src/utils/get-available-widgets.test.ts, packages/widget-picker/src/utils/get-available-widgets.ts
https://metakeen.atlassian.net/browse/FEE-149
=> fix: 🐛 select_unique widgets

packages/ui-core/src/components/modal/modal.component.tsx
https://metakeen.atlassian.net/browse/FEE-187
=> fix: 🐛 modal close handler

packages/widget-picker/src/utils/get-available-widgets.test.ts, packages/widget-picker/src/utils/get-available-widgets.ts
https://metakeen.atlassian.net/browse/FEE-191
=> fix: 🐛 set metric as a default chart

packages/charts/src/charts/table/table-chart.component.tsx, packages/charts/src/charts/table/table.utils.test.ts, packages/charts/src/charts/table/table.utils.tsx, packages/dataviz/src/utils/index.ts, packages/dataviz/src/utils/visualizer.utils.test.ts, packages/dataviz/src/utils/visualizer.utils.ts, packages/dataviz/src/visualizer.tsx, packages/parser/src/types.ts
https://metakeen.atlassian.net/browse/FEE-165
=> feat: 🎸 table columns order

packages/ui-core/src/components/modal/modal.component.test.tsx, packages/ui-core/src/components/modal/modal.component.tsx
https://metakeen.atlassian.net/browse/FEE-170
=> refactor: 💡 set blockScrollOnOpen to false by default

packages/ui-core/src/components/checkbox/checkbox.styles.ts
https://metakeen.atlassian.net/browse/FEE-256
=> fix: 🐛 checkbox styles

packages/ui-core/src/components/checkbox/__snapshots__/checkbox.component.test.tsx.snap, packages/ui-core/src/components/checkbox/checkbox.styles.ts
https://metakeen.atlassian.net/browse/FEE-270
=> style: 💄 reset styles for <Checkbox/>

packages/charts-utils/src/number/format-number/format-number.test.ts, packages/charts-utils/src/number/format-number/format-number.ts, packages/charts/src/charts/funnel/utils/chart.utils.test.ts, packages/charts/src/charts/funnel/utils/chart.utils.ts, packages/charts/src/charts/gauge/gauge-progress.component.test.tsx
https://metakeen.atlassian.net/browse/FEE-267
=> fix: 🐛 zero values in funnel

packages/ui-core/src/components/slider/__snapshots__/interval-slider.component.test.tsx.snap, packages/ui-core/src/components/slider/control/control.component.tsx
https://metakeen.atlassian.net/browse/FEE-219
=> fix: 🐛 control alignment

packages/widgets/src/components/area/area-chart.widget.tsx, packages/widgets/src/components/bar/bar-chart.widget.tsx, packages/widgets/src/components/bubble/bubble-chart.widget.tsx, packages/widgets/src/components/chart-widget/chart-widget.component.tsx, packages/widgets/src/components/chart-widget/chart-widget.styles.tsx, packages/widgets/src/components/chart-widget/chart-widget.test.tsx, packages/widgets/src/components/chart-widget/index.ts, packages/widgets/src/components/choropleth/choropleth-chart.widget.tsx, packages/widgets/src/components/donut/donut-chart.widget.tsx, packages/widgets/src/components/funnel/funnel-chart.widget.tsx, packages/widgets/src/components/gauge/gauge-chart.widget.tsx, packages/widgets/src/components/heatmap/heatmap-chart.widget.tsx, packages/widgets/src/components/index.ts, packages/widgets/src/components/line/line-chart.widget.tsx, packages/widgets/src/components/pie/pie-chart.widget.tsx
refactored chart widget + added missing units tests
=> refactor: 💡 chart widget

packages/ui-core/src/index.ts, packages/ui-core/src/utils/download.ts, packages/ui-core/src/utils/export-to-html.ts, packages/ui-core/src/utils/index.ts
https://metakeen.atlassian.net/browse/FEE-239
=> feat: 🎸 export-to-html

packages/ui-core/src/components/badge/badge.component.tsx, packages/ui-core/src/components/badge/badge.stories.tsx, packages/ui-core/src/components/badge/badge.styles.ts, packages/ui-core/src/utils/string.utils.test.ts, packages/ui-core/src/utils/string.utils.ts
[#FEE-103](https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-103)
=> feat: 🎸 Badge with truncated label added

packages/ui-core/src/components/tag-management/tag-management.component.tsx
[FEE-103](https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-103)
=> feat: 🎸 Added truncate property to badge inside tag-management

packages/ui-core/src/components/relative-time/relative-time.component.tsx, packages/ui-core/src/components/time-period/time-period.component.tsx
https://metakeen.atlassian.net/browse/FEE-397
=> feat: 🎸 disabled autofocus for <RelativeTime>

packages/dataviz/src/types.ts, packages/dataviz/src/utils/visualization.utils.ts, packages/dataviz/src/visualizer.tsx, packages/parser/package.json, packages/parser/src/transformations/categorical/categorical.ts, packages/parser/src/transformations/categorical/charts/bar-transformation.test.ts, packages/parser/src/transformations/categorical/charts/bar-transformation.ts, packages/parser/tsconfig.json, packages/widgets/tsconfig.json
Closes: [FEE-390](https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-390)
=> feat: 🎸 Grouped bar

packages/ui-core/src/components/table/table-cell.component.tsx
https://metakeen.atlassian.net/browse/FEE-435
=> fix: 🐛 display boolean value in table

packages/dataviz/src/stories/heatmap-chart.stories.tsx, packages/parser/src/analysis/count.test.ts, packages/parser/src/constants.ts, packages/parser/src/merge.test.ts, packages/parser/src/transformations/categorical-chronological/categorical-chronological.test.ts, packages/parser/src/transformations/categorical/categorical.test.ts, packages/parser/src/transformations/categorical/categorical.ts, packages/parser/src/transformations/categorical/charts/chart-transformation.test.ts, packages/parser/src/transformations/categorical/charts/chart-transformation.ts, packages/parser/src/utils/merge-properties-group/merge-properties-group.test.ts, packages/parser/src/utils/merge-properties-group/merge-properties-group.ts, packages/ui-core/src/components/properties-tree/utils/__snapshots__/createTree.test.ts.snap, packages/ui-core/src/components/properties-tree/utils/createTree.test.ts
https://metakeen.atlassian.net/browse/FEE-392
=> feat: 🎸 heatmap groups

docs/charts-intro.stories.mdx, packages/charts-utils/src/scale/format-scale-label/format-by-pattern.test.ts, packages/charts-utils/src/scale/format-scale-label/format-by-pattern.ts
Closes: [FEE-427](https://metakeen.atlassian.net/browse/FEE-427)
=> feat: 🎸 Added mathematical operations to scale settings

packages/charts/src/charts/metric/metric-chart.component.test.tsx, packages/charts/src/charts/metric/metric-chart.component.tsx, packages/charts/src/charts/metric/metric-chart.stories.tsx
https://metakeen.atlassian.net/browse/FEE-460
=> refactor: 💡 format value by pattern in metric chart

packages/charts/src/charts/circular-chart/tooltip-item.component.tsx, packages/charts/src/charts/circular-chart/tooltip-item.styles.tsx, packages/charts/src/charts/donut/donut-chart.component.test.tsx, packages/charts/src/charts/pie/pie-chart.component.test.tsx, packages/charts/src/utils/tooltip.utils.ts
https://metakeen.atlassian.net/browse/FEE-430
=> fix: 🐛 update letter spacing

packages/charts/src/charts/area/area-chart.component.tsx, packages/charts/src/charts/area/area-chart.stories.tsx, packages/charts/src/charts/line/components/tooltip/tooltip.component.tsx, packages/charts/src/charts/line/line-chart.component.tsx, packages/charts/src/charts/line/line-chart.stories.tsx
https://metakeen.atlassian.net/browse/FEE-468
=> feat: 🎸 format tooltip pattern for line/area

packages/charts/src/charts/heatmap/heatmap-chart.component.test.tsx, packages/charts/src/charts/heatmap/heatmap-chart.component.tsx, packages/charts/src/charts/heatmap/heatmap-chart.stories.tsx, packages/charts/src/charts/heatmap/tooltip-content.component.tsx
https://metakeen.atlassian.net/browse/FEE-465
=> refactor: 💡 format tooltip for heatmap

packages/charts/src/components/responsive-wrapper.component.tsx
https://metakeen.atlassian.net/browse/FEE-473
=> fix: 🐛 funnel chart responsiveness

packages/ui-core/src/components/index.ts, packages/ui-core/src/components/timezone/index.ts, packages/ui-core/src/index.ts
https://metakeen.atlassian.net/browse/FEE-404
=> chore: 🤖 export Timezones from ui-core

packages/typography/.babelrc, packages/typography/CHANGELOG.md, packages/typography/README.md, packages/typography/jest.config.js, packages/typography/jest.setup.ts, packages/typography/package.json, packages/typography/src/components/body-text/body-text.component.tsx, packages/typography/src/components/body-text/body-text.stories.tsx, packages/typography/src/components/body-text/index.ts, packages/typography/src/components/body-text/types.ts, packages/typography/src/components/font-weight/font-weight.component.tsx, packages/typography/src/components/font-weight/font-weight.stories.tsx, packages/typography/src/components/font-weight/index.ts, packages/typography/src/components/headline/constants.tsx, packages/typography/src/components/headline/headline.component.tsx, packages/typography/src/components/headline/headline.stories.tsx, packages/typography/src/components/headline/index.ts, packages/typography/src/components/headline/types.tsx, packages/typography/src/components/italic/index.ts, packages/typography/src/components/italic/italic.component.tsx, packages/typography/src/components/italic/italic.stories.tsx, packages/typography/src/components/underline/index.ts, packages/typography/src/components/underline/underline.component.tsx, packages/typography/src/components/underline/underline.stories.tsx, packages/typography/src/constants.ts, packages/typography/src/index.ts, packages/typography/src/types.ts, packages/typography/src/utils/index.ts, packages/typography/src/utils/resetSpacing.ts, packages/typography/tsconfig.json
https://metakeen.atlassian.net/browse/FEE-447
=> feat: 🎸 @keen.io/typography

packages/charts/src/charts/metric/metric-chart.component.test.tsx, packages/charts/src/charts/metric/metric-chart.component.tsx, packages/charts/src/charts/metric/utils/metric.utils.test.ts, packages/charts/src/charts/metric/utils/metric.utils.ts, packages/dataviz/src/stories/metric.stories.tsx, packages/widget-picker/src/utils/get-available-widgets.test.ts, packages/widget-picker/src/utils/get-available-widgets.ts
https://metakeen.atlassian.net/browse/FEE-364
=> chore: 🤖 metric chart updates

packages/ui-core/src/components/tabs/tabs.component.tsx, packages/ui-core/src/components/tabs/tabs.styles.ts
https://metakeen.atlassian.net/browse/FEE-492
https://user-images.githubusercontent.com/23423731/111616828-a4130280-87e2-11eb-8b8a-2bb1c7ae0293.mov
=> chore: 🤖 simplify tabs animation

packages/ui-core/src/components/dropable-container/dropable-container.component.tsx, packages/ui-core/src/components/dropable-container/dropable-container.styles.ts
Related PR: [#50](https://github.com/keen/query-creator/pull/50)
Ticket: [FEE-306](https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-306)
=> chore: 🤖  Droppable container content centered

packages/charts-utils/src/constants.ts, packages/charts-utils/src/index.ts, packages/charts-utils/src/time/get-precision-from-interval/index.ts, packages/charts-utils/src/time/index.ts, packages/charts/src/charts/gauge/constants.ts, packages/charts/src/charts/gauge/gauge-chart.component.tsx, packages/charts/src/charts/metric/metric-chart.component.tsx, packages/charts/src/constants.ts, packages/charts/src/theme.ts, packages/dataviz/src/stories/metric.stories.tsx, packages/dataviz/src/utils/chart-settings/index.ts, packages/dataviz/src/utils/chart-settings/metric-chart-settings.test.ts, packages/dataviz/src/utils/chart-settings/metric-chart-settings.ts, packages/dataviz/src/utils/chart-settings/types.ts, packages/dataviz/src/utils/create-settings-from-query.ts, packages/dataviz/src/utils/index.ts, packages/dataviz/src/visualizer.tsx, packages/query/src/types.ts, packages/widgets/src/components/metric/metric.widget.tsx
[FEE-365](https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-365)
=> feat: 🎸 Metric chart caption added

packages/charts/src/charts/bar/bar-chart.component.tsx, packages/charts/src/charts/line/components/lines/lines.component.tsx, packages/charts/src/charts/line/line-chart.component.tsx, packages/charts/src/components/distributed-chart-tooltip/distributed-chart-tooltip.component.test.tsx, packages/charts/src/components/distributed-chart-tooltip/distributed-chart-tooltip.component.tsx, packages/charts/src/components/distributed-chart-tooltip/hooks/use-distributed-tooltip.test.ts, packages/charts/src/components/distributed-chart-tooltip/hooks/use-distributed-tooltip.ts
https://metakeen.atlassian.net/browse/FEE-499
=> fix: 🐛 line/area chart tooltip updates

packages/ui-core/src/components/empty-search/empty-search.component.test.tsx, packages/ui-core/src/components/empty-search/empty-search.component.tsx, packages/ui-core/src/components/empty-search/empty-search.stories.tsx, packages/ui-core/src/components/empty-search/empty-search.styles.ts, packages/ui-core/src/components/empty-search/index.ts, packages/ui-core/src/components/index.ts, packages/ui-core/src/index.ts
https://metakeen.atlassian.net/browse/FEE-389
=> feat: 🎸 extract <EmptySearch> component

.storybook/main.js, docs/charts-intro.stories.mdx, docs/typography-intro.stories.mdx, docs/widgets-intro.stories.mdx, packages/typography/src/components/body-text/body-text.component.tsx, packages/typography/src/components/body-text/body-text.stories.tsx, packages/typography/src/components/font-weight/font-weight.component.tsx, packages/typography/src/components/font-weight/font-weight.stories.tsx, packages/typography/src/components/headline/headline.component.tsx, packages/typography/src/components/headline/headline.stories.tsx, packages/typography/src/components/headline/types.tsx, packages/typography/src/components/italic/italic.stories.tsx, packages/typography/src/components/underline/underline.stories.tsx
https://metakeen.atlassian.net/browse/FEE-504
=> feat: 🎸 extend Headline with h4 option

packages/widget-picker/src/components/widget-picker/widget-picker.styles.ts
https://metakeen.atlassian.net/browse/FEE-505
=> fix: 🐛 Widget picker z-index changed

packages/ui-core/src/components/dropable-container/dropable-container.component.tsx, packages/ui-core/src/components/index.ts, packages/ui-core/src/components/timezone/components/index.ts, packages/ui-core/src/components/timezone/components/timezone-error/index.ts, packages/ui-core/src/components/timezone/components/timezone-error/timezone-error.component.test.tsx, packages/ui-core/src/components/timezone/components/timezone-error/timezone-error.component.tsx, packages/ui-core/src/components/timezone/components/timezone-error/timezone-error.styles.ts, packages/ui-core/src/components/timezone/index.ts, packages/ui-core/src/components/timezone/timezone.stories.tsx
=> feat: 🎸 timezone error component

packages/charts/src/charts/funnel/components/header/header.component.tsx, packages/charts/src/charts/funnel/components/header/header.styles.ts, packages/charts/src/charts/funnel/components/step/step.styles.ts
https://metakeen.atlassian.net/browse/FEE-525
=> fix: 🐛 funnel step text truncate

packages/ui-core/src/components/dropable-container/dropable-container.stories.tsx, packages/ui-core/src/components/dropable-container/dropable-container.styles.ts, packages/ui-core/src/components/dropable-container/types.ts
Part of the solution to fix this bug: [FEE-536](https://metakeen.atlassian.net/browse/FEE-536)
=> feat: 🎸 Added transparent variant to dropable container

packages/ui-core/src/components/button/button.stories.tsx, packages/ui-core/src/components/button/button.styles.ts
Part of the solution from the ticket: [https://metakeen.atlassian.net/browse/FEE-547](https://metakeen.atlassian.net/browse/FEE-547)
=> feat: 🎸 Disabled button styles added

packages/ui-core/src/components/button/button.styles.ts
[https://metakeen.atlassian.net/browse/FEE-552](https://metakeen.atlassian.net/browse/FEE-552)
=> fix: 🐛 Disabled button highlight turned off

packages/charts/src/charts/metric/metric-chart.component.test.tsx, packages/charts/src/charts/metric/metric-chart.component.tsx
Closes: [FEE-562](https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-562)
=> fix: 🐛 Secondary value metric formatter

packages/charts/src/charts/circular-chart/tooltip-item.component.tsx, packages/charts/src/components/legend/label/label.component.tsx
Fixes: [FEE-557](https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-557)
=> fix: 🐛 Missing legend labels - boolean to string

packages/charts/src/components/distributed-chart-tooltip/hooks/use-distributed-tooltip.ts, packages/charts/src/components/tooltip-content/tooltip-content.component.tsx, packages/dataviz/src/stories/bar-chart.stories.tsx
[FEE-561](https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-561)
=> fix: 🐛 Bar chart - total value in tooltip formatter applied

packages/ui-core/src/components/dropdown/dropdown.styles.ts
https://user-images.githubusercontent.com/23423731/115349651-6542e480-a1b4-11eb-9314-b68f28c8817c.mov
=> fix: 🐛 remove <Dropdown> shake while animating

packages/charts/src/charts/metric/metric-chart.component.tsx
https://metakeen.atlassian.net/browse/FEE-566
=> fix: 🐛 update metric chart tooltip position

packages/ui-core/src/components/checkbox/__snapshots__/checkbox.component.test.tsx.snap, packages/ui-core/src/components/checkbox/checkbox.styles.ts
https://metakeen.atlassian.net/browse/FEE-586
=> fix: 🐛 Checkbox alignment

packages/ui-core/src/components/properties-tree/components/tree-leaf/tree-leaf.component.tsx, packages/ui-core/src/components/properties-tree/components/tree-leaf/tree-leaf.styles.ts, packages/ui-core/src/components/properties-tree/components/tree-node/tree-node.component.tsx, packages/ui-core/src/components/properties-tree/components/tree-node/tree-node.styles.ts
https://metakeen.atlassian.net/browse/FEE-585
=> fix: 🐛 PropertiesTree line height

packages/charts/src/charts/funnel/funnel-chart.component.test.tsx, packages/charts/src/charts/funnel/funnel-chart.component.tsx
https://metakeen.atlassian.net/browse/FEE-594
=> fix: 🐛 remove default format value for funnel

packages/ui-core/src/components/mouse-positioned-tooltip/index.ts, packages/ui-core/src/components/mouse-positioned-tooltip/mouse-positioned-tooltip.stories.tsx, packages/ui-core/src/components/mouse-positioned-tooltip/mouse-positioned-tooltip.styles.ts, packages/ui-core/src/components/mouse-positioned-tooltip/mouse-positioned-tooltip.tsx, packages/ui-core/src/components/mouse-positioned-tooltip/types.ts, packages/ui-core/src/components/mouse-positioned-tooltip/utils/getTooltipTranslation.test.ts, packages/ui-core/src/components/mouse-positioned-tooltip/utils/getTooltipTranslation.ts, packages/widgets/src/components/choropleth/components/chart-interaction-legend/chart-interaction-legend.component.tsx
[FEE-615](https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-615)
=> fix: 🐛 Tooltip pin to cursor position

packages/parser/src/transformations/categorical/charts/table-transformation.ts
https://metakeen.atlassian.net/browse/FEE-500
=> fix: 🐛 categorical transformation for table

packages/charts/src/charts/donut/donut-chart.component.tsx, packages/charts/src/charts/donut/donut-slice.component.tsx, packages/charts/src/charts/pie/pie-chart.component.tsx, packages/charts/src/charts/pie/pie-slice.component.tsx, packages/charts/src/charts/pie/utils/getActiveKeyVariants.ts, packages/charts/src/charts/pie/utils/index.ts, packages/charts/src/types.ts, packages/widgets/src/components/donut/donut-chart.widget.tsx, packages/widgets/src/components/pie/pie-chart.widget.tsx
https://metakeen.atlassian.net/browse/FEE-542
=> feat: 🎸 pie/donut legend interactions

packages/charts/src/charts/bar/bar-chart.component.tsx, packages/charts/src/charts/bar/components/bar/bar.component.tsx, packages/charts/src/charts/bar/components/bars/bars.component.tsx, packages/charts/src/charts/bar/utils/animate.utils.ts, packages/widgets/src/components/bar/bar-chart.widget.tsx
https://metakeen.atlassian.net/browse/FEE-543
=> feat: 🎸 bar chart legend interactions

packages/charts/src/charts/heatmap/heatmap-chart.component.tsx, packages/charts/src/charts/heatmap/types.ts, packages/charts/src/charts/heatmap/utils/__snapshots__/heatmap-chart.utils.test.ts.snap, packages/charts/src/charts/heatmap/utils/heatmap-chart.utils.ts, packages/ui-core/src/components/modal/modal.component.test.tsx, packages/ui-core/src/components/modal/modal.component.tsx
- Created configuration that allows to disable modal close when users clicks on fade mask
- Heatmap respects theme colors
=> feat: 🎸 modal fade mask close + heatmap respect theme colors

packages/ui-core/src/components/accordion/accordion.component.tsx, packages/ui-core/src/components/accordion/accordion.stories.tsx, packages/ui-core/src/components/accordion/accordion.styles.ts, packages/ui-core/src/components/accordion/accordion.test.tsx, packages/ui-core/src/components/accordion/index.ts, packages/ui-core/src/components/accordion/motion.ts, packages/ui-core/src/components/index.ts, packages/ui-core/src/index.ts
https://metakeen.atlassian.net/browse/FEE-635
=> feat: 🎸 Accordion component

packages/charts/src/components/legend/card/card.component.tsx, packages/charts/src/components/legend/card/card.styles.ts, packages/charts/src/components/legend/legend-base.component.tsx, packages/charts/src/components/legend/legend.styles.tsx, packages/charts/src/components/legend/series/series-horizontal.component.tsx, packages/charts/src/components/legend/series/series-vertical.component.tsx, packages/charts/src/components/legend/series/series.component.tsx, packages/charts/src/components/legend/types.ts, packages/storybook-utils/src/card.knobs.ts, packages/ui-core/src/components/card/card.component.tsx, packages/ui-core/src/components/modal/modal.component.tsx, packages/widgets/src/components/table/table-chart.widget.tsx
https://metakeen.atlassian.net/browse/FEE-262
FEE-667, FEE-668
=> feat: 🎸 Added new props to Card component

packages/ui-core/src/components/index.ts, packages/ui-core/src/components/slider/index.ts, packages/ui-core/src/components/slider/interval-slider.stories.tsx, packages/ui-core/src/components/slider/utils/interval.utils.ts, packages/ui-core/src/index.ts
https://metakeen.atlassian.net/browse/FEE-666
=> feat: 🎸 slider for theming

packages/ui-core/src/components/color-palette/color-palette.styles.tsx, packages/ui-core/src/components/color-palette/components/color/color.styles.ts
https://metakeen.atlassian.net/browse/FEE-632
=> fix: 🐛 color palette spacing

packages/ui-core/src/components/slider/interval-slider.component.tsx
https://metakeen.atlassian.net/browse/FEE-644
=> fix: 🐛 update handleClick dependencies for IntervalSlider

packages/ui-core/src/components/modal/modal.styles.ts
https://metakeen.atlassian.net/browse/FEE-687
=> fix: 🐛 FadeMask background animation

packages/charts/src/theme.ts, packages/ui-core/src/components/slider/range-slider.component.tsx, packages/ui-core/src/components/slider/types.ts, packages/widgets/src/components/choropleth/choropleth-chart.widget.tsx, packages/widgets/src/components/choropleth/components/chart-interaction-legend/chart-interaction-legend.component.tsx, packages/widgets/src/components/heatmap/heatmap-chart.widget.tsx
[https://metakeen.atlassian.net/browse/FEE-472](https://metakeen.atlassian.net/browse/FEE-472)
=> feat: 🎸 Light mode applied to chart tooltips

packages/ui-core/src/components/color-palette/color-palette.component.test.tsx, packages/ui-core/src/components/color-palette/components/color/color.component.test.tsx, packages/ui-core/src/components/color-picker/color-picker.component.test.tsx
Fixed old tests console errors
=> fix: 🐛 Color picker components tests - errors in console fixed

packages/widgets/src/widget-settings.ts
Legend default size changed: https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-645
=> chore: 🤖 Legend default font size changed

packages/charts/src/charts/table/table-chart.component.tsx, packages/charts/src/charts/table/table.stories.tsx, packages/charts/src/theme.ts, packages/charts/src/types.ts, packages/dataviz/src/utils/chart-settings/table-chart-settings.ts, packages/widgets/src/components/table/table-chart.widget.stories.tsx
- Moved table color property used for main background color to theme object as part of next theming iteration in Dashboard Creator.
=> chore: 🤖 table color

packages/charts/src/charts/line/line-chart.component.tsx, packages/charts/src/charts/line/line-chart.stories.tsx, packages/charts/src/charts/line/utils/marks.utils.test.ts, packages/charts/src/theme.ts, packages/charts/src/types.ts
- Line chart settings moved to theme
=> feat: 🎸 line chart theme

packages/ui-core/src/components/modal/modal.component.tsx
https://metakeen.atlassian.net/browse/FEE-498
=> fix: 🐛 set scroll position once the modal is open

packages/ui-core/src/components/side-menu/side-menu.styles.ts
* Add shadow and rounding to the navigation active element
* Add hover state to the navigation
=> style: 💄 update SideMenu styles

.circleci/config.yml
added --no-verify-access to omit permission check in pipeline
=> ci: 🎡 lerna no verify access

packages/ui-core/src/components/accordion/accordion.component.tsx, packages/ui-core/src/components/accordion/accordion.styles.ts, packages/ui-core/src/components/accordion/motion.ts
https://metakeen.atlassian.net/browse/FEE-734
=> fix: 🐛 animation glitch for accordion

packages/charts/src/charts/table/table-chart.component.tsx, packages/charts/src/charts/table/table.stories.tsx, packages/charts/src/charts/table/types.ts, packages/charts/src/charts/table/utils/chart.utils.test.ts, packages/charts/src/charts/table/utils/chart.utils.ts
https://metakeen.atlassian.net/browse/FEE-787
=> feat: 🎸 enhance table formatters

packages/charts/src/charts/table/components/header-row/__snapshots__/header-row.component.test.tsx.snap, packages/charts/src/charts/table/components/header-row/header-row.component.tsx, packages/charts/src/charts/table/components/header-row/header-row.styles.ts, packages/charts/src/charts/table/table-chart.component.tsx, packages/charts/src/charts/table/table-chart.styles.ts, packages/ui-core/src/components/table/table-cell.component.tsx, packages/ui-core/src/components/table/table-cell.styles.ts, packages/ui-core/src/components/table/table-row.component.tsx, packages/ui-core/src/components/table/table-row.styles.ts
https://metakeen.atlassian.net/browse/FEE-769
=> table column selection

packages/ui-core/src/components/button/button.stories.tsx, packages/ui-core/src/components/button/button.styles.ts
https://metakeen.atlassian.net/browse/FEE-768
=> style: 💄 disabled state for success button

packages/charts/src/charts/choropleth/choropleth-chart.component.tsx, packages/charts/src/charts/choropleth/types.ts, packages/charts/src/charts/heatmap/heatmap-chart.component.tsx, packages/charts/src/charts/heatmap/types.ts, packages/ui-core/src/components/slider/interval-slider.component.tsx, packages/ui-core/src/components/slider/range-slider.component.tsx, packages/ui-core/src/components/slider/types.ts, packages/widgets/src/components/choropleth/choropleth-chart.widget.stories.tsx, packages/widgets/src/components/choropleth/choropleth-chart.widget.tsx, packages/widgets/src/components/heatmap/heatmap-chart.widget.stories.tsx, packages/widgets/src/components/heatmap/heatmap-chart.widget.tsx
https://metakeen.atlassian.net/browse/FEE-778
=> fix: 🐛 apply formatters to slider

packages/widgets/src/components/error/error.widget.styles.ts, packages/widgets/src/components/error/error.widget.tsx
https://metakeen.atlassian.net/browse/FEE-749
=> style: 💄 ErrorWidget component

packages/widget-picker/src/utils/get-available-widgets.test.ts, packages/widget-picker/src/utils/get-available-widgets.ts
https://metakeen.atlassian.net/browse/FEE-341
=> feat: 🎸 add support for multi-analysis

packages/typography/src/components/body-text/body-text.component.tsx, packages/typography/src/components/headline/headline.component.tsx
https://metakeen.atlassian.net/browse/FEE-839
=> style: 💄 extend BodyText and Headline with text-transform

packages/dev-tools/README.md, packages/dev-tools/package.json, packages/dev-tools/src/createRollupConfig.ts, packages/dev-tools/src/index.ts, packages/dev-tools/tsconfig.json, packages/dev-tools/types/rollup-plugin-peer-deps-external/index.d.ts, packages/typography/package.json, packages/typography/rollup.config.js, packages/typography/tsconfig.json, packages/ui-core/package.json, packages/ui-core/rollup.config.js, packages/ui-core/tsconfig.json, yarn.lock
- This pull request introduces a new approach for building library artifacts with usage of rollup bundler
- @keen.io/ui-core and @keen.io/typography packages will be easily tree-shakable during Webpack builds
=> chore: 🤖 introduce rollup for bundling libs

packages/charts/src/charts/table/components/body-cell/body-cell.tsx, packages/charts/src/charts/table/components/body/body.component.tsx, packages/charts/src/charts/table/components/header-cell-content/header-cell-content.ts, packages/charts/src/charts/table/components/header/header.component.tsx, packages/charts/src/charts/table/components/header/header.styles.ts, packages/charts/src/charts/table/components/selection-column/cell/cell.component.tsx, packages/charts/src/charts/table/components/selection-column/header/header.component.tsx, packages/charts/src/charts/table/table-chart.component.tsx, packages/charts/src/charts/table/types.ts
- Row selection disabled  in table edit mode
- Row selection column width fix
=> chore: 🤖 Disabled row selection column, width fix

packages/ui-core/src/components/alert/alert.component.tsx, packages/ui-core/src/components/alert/alert.stories.tsx, packages/ui-core/src/components/alert/alert.styles.ts
=> feat: 🎸 enhance Alert with content width

packages/charts/src/charts/table/components/body-cell/body-cell.tsx
to handle date-time formatter: https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-828
=> chore: 🤖 Allowing multiple spaces in table cell body

packages/ui-core/src/components/absolute-time/absolute-time.test.tsx, packages/ui-core/src/components/date-picker/date-picker.component.tsx
https://metakeen.atlassian.net/browse/FEE-864
=> fix: 🐛 prevent time reset in DatePicker

packages/ui-core/src/components/dropdown-list/dropdown-list.component.tsx, packages/ui-core/src/components/tag-management/tag-management.component.tsx, packages/ui-core/src/components/tag-management/tag-management.stories.tsx, packages/ui-core/src/components/tag-management/tag-management.styles.ts, packages/ui-core/src/components/time-period/time-period.test.tsx
https://metakeen.atlassian.net/browse/FEE-318
=> fix: 🐛 scroll Dropdown item into view

packages/ui-core/src/components/dropdown-list-container/dropdown-list-container.component.tsx, packages/ui-core/src/components/dropdown-list-container/dropdown-list-container.styles.ts, packages/ui-core/src/components/dropdown-list/dropdown-list.component.tsx, packages/ui-core/src/components/dropdown-list/dropdown-list.styles.ts, packages/ui-core/src/components/tag-management/tag-management.component.test.tsx, packages/ui-core/src/components/time-period/time-period.test.tsx
- scroll shadow added to dropdown list container
- passing padding as a prop to dropdown list - in order to clear top padding in filter suggestions dropdown in query creator.
=> feat: 🎸 Dropdown list shadow, padding from props

packages/dataviz/src/visualizer.test.ts, packages/dataviz/src/visualizer.tsx
https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-816
=> fix: 🐛 Empty visualization fix

packages/data-export/src/transformations/gauge/constants.ts, packages/data-export/src/transformations/gauge/index.ts, packages/data-export/src/transformations/gauge/transform.test.ts, packages/data-export/src/transformations/gauge/transform.ts, packages/data-export/src/transformations/settings.ts
https://metakeen.atlassian.net/browse/FEE-877
=> fix: 🐛 data export for Gauge

packages/ui-core/src/components/date-picker/date-picker.component.tsx
https://metakeen.atlassian.net/browse/FEE-849
=> fix: 🐛 typing handlers in inputs

packages/charts/src/charts/table/table-chart.component.tsx, packages/ui-core/src/components/table-footer/constants.ts, packages/ui-core/src/components/table-footer/table-footer.component.test.tsx, packages/ui-core/src/components/table-footer/table-footer.component.tsx, packages/ui-core/src/components/table-footer/table-footer.styles.ts
https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-869
=> feat: 🎸 Table pagination settings

packages/charts/src/charts/heatmap/constants.ts, packages/charts/src/charts/heatmap/heatmap-chart.component.tsx, packages/dataviz/src/stories/heatmap-chart.stories.tsx, packages/widgets/src/components/heatmap/components/too-many-groups-error/index.ts, packages/widgets/src/components/heatmap/components/too-many-groups-error/text.json, packages/widgets/src/components/heatmap/components/too-many-groups-error/too-many-groups-error.component.tsx, packages/widgets/src/components/heatmap/components/too-many-groups-error/too-many-groups-error.styles.ts, packages/widgets/src/components/heatmap/heatmap-chart.widget.tsx
https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-524
=> feat: 🎸 Heatmap - to many groups error

.gitignore, packages/charts-utils/package.json, packages/colors/package.json, packages/colors/rollup.config.ts, packages/colors/tsconfig.json, packages/icons/package.json, packages/icons/rollup.config.ts, packages/icons/tsconfig.json, packages/query/package.json, packages/query/rollup.config.ts, packages/query/tsconfig.json, packages/react-hooks/package.json, packages/react-hooks/rollup.config.ts, packages/react-hooks/tsconfig.json, packages/ui-core/package.json, packages/ui-core/rollup.config.js, packages/ui-core/rollup.config.ts, packages/ui-core/tsconfig.json
- Updates `package.json` references to proper modules files (ESM + CommonJS).
=> chore: 🤖 ES modules for NPM packages
